<H1>STATUS</H1>
<table>
    <tr>
        <td>nama</td>
        <td>:</td>
        <td><span>{{$nama}}</span></td>
    </tr>
    <tr>
        <td>status</td>
        <td>:</td>
        <td><span>{{$status}}</span></td>
    </tr>
</table>